export default [
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 1,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 2,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 3,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 4,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 5,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 6,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 7,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 8,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 9,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 10,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 11,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 12,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 13,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 14,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 15,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 16,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 17,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 18,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 19,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 20,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 21,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 22,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 23,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 24,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 25,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 26,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 27,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 28,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 29,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 30,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 31,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 32,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 32,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 33,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 34,
    },
    {
        name: "Тестовое название",
        description: "Тестовое писание карточки. Подробное и понятное, в несколько строчек",
        image_url: "https://random.imagecdn.app/500/150",
        price: 12000,
        id: 35,
    },

]